Unity HDRP Product Visualizer: CanMaterialSwapper Class Reference
CanMaterialSwapper Class Reference
Cycles through brand variants by replacing the full material array on the can renderer.
Public Member Functions
void NextVariant ()
Advances to the next variant, wrapping around the list.
void PreviousVariant ()
Steps back to the previous variant, wrapping around the list.
void SetVariantIndex (int index)
Jumps directly to a variant by index.
Public Attributes
Renderer canRenderer
The Renderer whose material array will be swapped.
List< CanVariant > variants = new()
Ordered list of brand variants available in the visualizer.
System.Action< int, CanVariant > OnVariantChanged
Fired after a variant change with (newIndex, newVariant).
Properties
CanVariant CurrentVariant [get]
The currently active CanVariant, or null if the list is empty.
int CurrentIndex [get]
Zero-based index of the active variant.
int VariantCount [get]
Total number of registered variants.
string CurrentVariantName [get]
Display name of the active variant (empty string if none).
Detailed Description
Cycles through brand variants by replacing the full material array on the can renderer.
The soda can FBX (Resources/Prefabs/Can) exposes exactly two material slots:
Slot Region Changed per variant?
0 Label / body Yes
1 Aluminium caps No (shared)
Why material swap instead of MaterialPropertyBlock?
The brand textures require entirely separate material assets because _BaseColorMap cannot be overridden per-renderer without creating a material instance anyway. A full swap is simpler and equally performant for a single-object visualizer.
Integration
Wire canRenderer in the Inspector (or let Start() auto-detect it), then populate variants. VisualizerUI calls NextVariant() / PreviousVariant() in response to UI button presses.
Definition at line 49 of file CanMaterialSwapper.cs.
Member Function Documentation
NextVariant()
void CanMaterialSwapper.NextVariant ()
Advances to the next variant, wrapping around the list.
Definition at line 97 of file CanMaterialSwapper.cs.
References OnVariantChanged, and variants.
PreviousVariant()
void CanMaterialSwapper.PreviousVariant ()
Steps back to the previous variant, wrapping around the list.
Definition at line 105 of file CanMaterialSwapper.cs.
References OnVariantChanged, and variants.
SetVariantIndex()
void CanMaterialSwapper.SetVariantIndex (int index)
Jumps directly to a variant by index.
Parameters
index Zero-based index into variants. Out-of-range values are ignored.
Definition at line 114 of file CanMaterialSwapper.cs.
References OnVariantChanged, and variants.
Member Data Documentation
canRenderer
Renderer CanMaterialSwapper.canRenderer
The Renderer whose material array will be swapped.
Auto-detected via GetComponentInChildren if left null.
Definition at line 58 of file CanMaterialSwapper.cs.
OnVariantChanged
System.Action<int, CanVariant> CanMaterialSwapper.OnVariantChanged
Fired after a variant change with (newIndex, newVariant).
Subscribe in VisualizerUI to update on-screen labels.
Definition at line 72 of file CanMaterialSwapper.cs.
Referenced by NextVariant(), PreviousVariant(), and SetVariantIndex().
variants
List<CanVariant> CanMaterialSwapper.variants = new()
Ordered list of brand variants available in the visualizer.
Populated automatically by ProductVisualizerSetup from the textures found in Assets/Resources/textures/.
Definition at line 64 of file CanMaterialSwapper.cs.
Referenced by NextVariant(), PreviousVariant(), and SetVariantIndex().
Property Documentation
CurrentIndex
int CanMaterialSwapper.CurrentIndex get
Zero-based index of the active variant.
Definition at line 126 of file CanMaterialSwapper.cs.
CurrentVariant
CanVariant CanMaterialSwapper.CurrentVariant get
The currently active CanVariant, or null if the list is empty.
Definition at line 123 of file CanMaterialSwapper.cs.
CurrentVariantName
string CanMaterialSwapper.CurrentVariantName get
Display name of the active variant (empty string if none).
Definition at line 132 of file CanMaterialSwapper.cs.
VariantCount
int CanMaterialSwapper.VariantCount get
Total number of registered variants.
Definition at line 129 of file CanMaterialSwapper.cs.
The documentation for this class was generated from the following file:
UnityVisualizer/Assets/ProductVisualizer/Scripts/CanMaterialSwapper.cs